os: osx
language: objective-c
osx_image: xcode10
podfile: ./MERLin/Podfile
xcode_workspace: ./MERLin/MERLin.xcworkspace
xcode_scheme: MERLin
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X